# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "nightly-2021-05-07"
components = [ "rustfmt", "rustc", "rust-src" ]
targets = ["armv7-unknown-linux-gnueabihf"]
